---
- name: Check cogmoteGO API Status
  hosts: all
  gather_facts: true
  ignore_unreachable: false

  tasks:
    - name: Query cogmoteGO API status endpoint
      ansible.builtin.uri:
        url: http://localhost:9012/api/status
        method: GET
        return_content: true
        timeout: 5
      register: status_response
      failed_when: false

    - name: Set is_running fact
      ansible.builtin.set_fact:
        is_running: "{{ status_response.json.is_running if (status_response.json is defined) else false }}"

    - name: Print status
      ansible.builtin.debug:
        msg: "Service running status is: {{ is_running }}"

    - name: Query cogmoteGO default broadcast data (latest) when running
      ansible.builtin.uri:
        url: http://localhost:9012/api/broadcast/data/default/latest
        method: GET
        return_content: true
        timeout: 5
      register: default_data_response
      failed_when: false
      when: is_running | bool

    - name: Pretty print default broadcast data (if not empty)
      ansible.builtin.debug:
        msg: "{{ default_data_response.json | to_nice_json }}"
      when:
        - is_running | bool
        - default_data_response.json is defined
        - default_data_response.json | length > 0
